default:
  options:
    gfxbackend: sdl2
    video_threaded: true
    audio.bgmusic:  0
    retroarch.video_rotation: 0 # for people upgrading
    # menu retroarch
    retroarch.menu_driver: rgui
    retroarch.rgui_menu_color_theme: 35
    retroarch.menu_scale_factor: "1.500000"
    retroarch.audio_driver: alsathread
    retroarch.config_save_on_exit: true
    retroarch.savestate_auto_save: true
    retroarch.network_cmd_enable: true
    retroarch.input_menu_toggle_btn: 14
    retroarch.input_load_state_btn: 7
    retroarch.input_save_state_btn: 8
    retroarch.input_reset_btn: 3
    retroarch.input_toggle_fast_forward_btn: 13
    retroarch.input_toggle_slowmotion_btn: 12

nds:
  emulator: drastic
  core:     drastic
fmtowns:
  emulator: libretro
  core:     mame
flash:
  emulator: lightspark
  core:     lightspark
atomiswave:
  emulator: libretro
  core:     flycastvl
dreamcast:
  emulator: libretro
  core:     flycastvl
naomi:
  emulator: libretro
  core:     flycastvl
